version: '3.8'
services:
  pdf-converter:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .streamlit:/app/.streamlit
    restart: always
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0